package errors

import "net/http"

/* Synapse Unified Standard Error Code List */

var (
	// 000000~00099 for all kinds of unknown errors, TODO to define necessary if need
	GenericUnknownError = NewStandardErrorCode(UnknownError, "GenericUnknownError", 000_000)
	UnknownType         = NewStandardErrorCode(UnknownError, "UnknownType", 000_001)
	UnknownProperty     = NewStandardErrorCode(UnknownError, "UnknownProperty", 000_002)
	UnknownKey          = NewStandardErrorCode(UnknownError, "UnknownKey", 000_003)
	UnknownValue        = NewStandardErrorCode(UnknownError, "UnknownValue", 000_004)
	UnknownDataBase     = NewStandardErrorCode(UnknownError, "UnknownDataBase", 000_005)
	UnknownTable        = NewStandardErrorCode(UnknownError, "UnknownTable", 000_006)
	UnknownField        = NewStandardErrorCode(UnknownError, "UnknownField", 000_007)
	UnknownDomain       = NewStandardErrorCode(UnknownError, "UnknownDomain", 8)
	UnknownEntity       = NewStandardErrorCode(UnknownError, "UnknownEntity", 9)
	UnknownAttribute    = NewStandardErrorCode(UnknownError, "UnknownAttribute", 10)

	// 000100~000599 HttpStatusXXX for HTTP error, TODO to define more if necessary， see http.XXX
	HttpStatusBadRequest                    = NewStandardErrorCode(HttpError, http.StatusText(http.StatusBadRequest), http.StatusUnauthorized)
	HttpStatusForbidden                     = NewStandardErrorCode(HttpError, http.StatusText(http.StatusForbidden), http.StatusForbidden)
	HttpStatusNotFound                      = NewStandardErrorCode(HttpError, http.StatusText(http.StatusNotFound), http.StatusNotFound)
	HttpStatusMethodNotAllowed              = NewStandardErrorCode(HttpError, http.StatusText(http.StatusMethodNotAllowed), http.StatusMethodNotAllowed)
	HttpStatusNotAcceptable                 = NewStandardErrorCode(HttpError, http.StatusText(http.StatusNotAcceptable), http.StatusNotAcceptable)
	HttpStatusProxyAuthRequired             = NewStandardErrorCode(HttpError, http.StatusText(http.StatusProxyAuthRequired), http.StatusProxyAuthRequired)
	HttpStatusRequestTimeout                = NewStandardErrorCode(HttpError, http.StatusText(http.StatusRequestTimeout), http.StatusRequestTimeout)
	HttpStatusRequestEntityTooLarge         = NewStandardErrorCode(HttpError, http.StatusText(http.StatusRequestEntityTooLarge), http.StatusRequestEntityTooLarge)
	HttpStatusRequestURITooLong             = NewStandardErrorCode(HttpError, http.StatusText(http.StatusRequestURITooLong), http.StatusRequestURITooLong)
	HttpStatusLocked                        = NewStandardErrorCode(HttpError, http.StatusText(http.StatusLocked), http.StatusLocked)
	HttpStatusTooEarly                      = NewStandardErrorCode(HttpError, http.StatusText(http.StatusTooEarly), http.StatusTooEarly)
	HttpStatusTooManyRequests               = NewStandardErrorCode(HttpError, http.StatusText(http.StatusTooManyRequests), http.StatusTooManyRequests)
	HttpStatusRequestHeaderFieldsTooLarge   = NewStandardErrorCode(HttpError, http.StatusText(http.StatusRequestHeaderFieldsTooLarge), http.StatusRequestHeaderFieldsTooLarge)
	HttpStatusInternalServerError           = NewStandardErrorCode(HttpError, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
	HttpStatusNotImplemented                = NewStandardErrorCode(HttpError, http.StatusText(http.StatusNotImplemented), http.StatusNotImplemented)
	HttpStatusBadGateway                    = NewStandardErrorCode(HttpError, http.StatusText(http.StatusBadGateway), http.StatusBadGateway)
	HttpStatusServiceUnavailable            = NewStandardErrorCode(HttpError, http.StatusText(http.StatusServiceUnavailable), http.StatusServiceUnavailable)
	HttpStatusGatewayTimeout                = NewStandardErrorCode(HttpError, http.StatusText(http.StatusGatewayTimeout), http.StatusGatewayTimeout)
	HttpStatusHTTPVersionNotSupported       = NewStandardErrorCode(HttpError, http.StatusText(http.StatusHTTPVersionNotSupported), http.StatusHTTPVersionNotSupported)
	HttpStatusInsufficientStorage           = NewStandardErrorCode(HttpError, http.StatusText(http.StatusInsufficientStorage), http.StatusInsufficientStorage)
	HttpStatusNetworkAuthenticationRequired = NewStandardErrorCode(HttpError, http.StatusText(http.StatusNetworkAuthenticationRequired), http.StatusNetworkAuthenticationRequired)

	// 100000~100999 reserved for pb/RPC/gRPC network error, TODO to define more if necessary
	GenericRpcError = NewStandardErrorCode(RpcError, "GenericRpcError", 100_000)

	// 101000~101999 for User Error
	GenericUserError            = NewStandardErrorCode(UserError, "GenericUserError", 101_000)
	SyntaxError                 = NewStandardErrorCode(UserError, "SyntaxError", 101_001)
	AbandonedQuery              = NewStandardErrorCode(UserError, "AbandonedQuery", 101_002)
	UserCanceled                = NewStandardErrorCode(UserError, "UserCanceled", 101_003)
	PermissionDenied            = NewStandardErrorCode(UserError, "PermissionDenied", 101_004)
	NotFound                    = NewStandardErrorCode(UserError, "NotFound", 101_005)
	FunctionNotFound            = NewStandardErrorCode(UserError, "FunctionNotFound", 101_006)
	InvalidFunctionArgument     = NewStandardErrorCode(UserError, "InvalidFunctionArgument", 101_007)
	DivisionByZero              = NewStandardErrorCode(UserError, "DivisionByZero", 101_008)
	InvalidCastArgument         = NewStandardErrorCode(UserError, "InvalidCastArgument", 101_009)
	OperatorNotFound            = NewStandardErrorCode(UserError, "OperatorNotFound", 101_010)
	InvalidView                 = NewStandardErrorCode(UserError, "InvalidView", 101_011)
	AlreadyExists               = NewStandardErrorCode(UserError, "AlreadyExists", 101_012)
	NotSupported                = NewStandardErrorCode(UserError, "NotSupported", 101_013)
	InvalidSessionProperty      = NewStandardErrorCode(UserError, "InvalidSessionProperty", 101_014)
	InvalidWindowFrame          = NewStandardErrorCode(UserError, "InvalidWindowFrame", 101_015)
	ConstraintViolation         = NewStandardErrorCode(UserError, "ConstraintViolation", 101_016)
	TransactionConflict         = NewStandardErrorCode(UserError, "TransactionConflict", 101_017)
	InvalidTableProperty        = NewStandardErrorCode(UserError, "InvalidTableProperty", 101_018)
	NumericValueOutOfRange      = NewStandardErrorCode(UserError, "NumericValueOutOfRange", 101_019)
	UnknownTransaction          = NewStandardErrorCode(UserError, "UnknownTransaction", 101_020)
	NotInTransaction            = NewStandardErrorCode(UserError, "NotInTransaction", 101_021)
	TransactionAlreadyAborted   = NewStandardErrorCode(UserError, "TransactionAlreadyAborted", 101_022)
	ReadOnlyViolation           = NewStandardErrorCode(UserError, "ReadOnlyViolation", 101_023)
	MultiCatalogWriteConflict   = NewStandardErrorCode(UserError, "MultiCatalogWriteConflict", 101_024)
	AutoCommitWriteConflict     = NewStandardErrorCode(UserError, "AutoCommitWriteConflict", 101_025)
	UnsupportedIsolationLevel   = NewStandardErrorCode(UserError, "UnsupportedIsolationLevel", 101_026)
	IncompatibleClient          = NewStandardErrorCode(UserError, "IncompatibleClient", 101_027)
	SubQueryMultipleRows        = NewStandardErrorCode(UserError, "SubQueryMultipleRows", 101_028)
	ProcedureNotFound           = NewStandardErrorCode(UserError, "ProcedureNotFound", 101_029)
	InvalidProcedureArgument    = NewStandardErrorCode(UserError, "InvalidProcedureArgument", 101_030)
	QueryRejected               = NewStandardErrorCode(UserError, "QueryRejected", 101_031)
	AmbiguousFunctionCall       = NewStandardErrorCode(UserError, "AmbiguousFunctionCall", 101_032)
	InvalidSchemaProperty       = NewStandardErrorCode(UserError, "InvalidSchemaProperty", 101_033)
	SchemaNotEmpty              = NewStandardErrorCode(UserError, "SchemaNotEmpty", 101_034)
	QueryTextTooLarge           = NewStandardErrorCode(UserError, "QueryTextTooLarge", 101_035)
	UnsupportedSubQuery         = NewStandardErrorCode(UserError, "UnsupportedSubQuery", 101_036)
	ExceededFunctionMemoryLimit = NewStandardErrorCode(UserError, "ExceededFunctionMemoryLimit", 101_037)
	AdministrativelyKilled      = NewStandardErrorCode(UserError, "AdministrativelyKilled", 101_038)
	InvalidColumnProperty       = NewStandardErrorCode(UserError, "InvalidColumnProperty", 101_039)
	QueryHasTooManyStages       = NewStandardErrorCode(UserError, "QueryHasTooManyStages", 101_040)
	InvalidSpatialPartitioning  = NewStandardErrorCode(UserError, "InvalidSpatialPartitioning", 101_041)
	InvalidAnalyzeProperty      = NewStandardErrorCode(UserError, "InvalidAnalyzeProperty", 101_042)
	GeneratedByteCodeTooLarge   = NewStandardErrorCode(UserError, "GeneratedByteCodeTooLarge", 101_043)
	WarningAsError              = NewStandardErrorCode(UserError, "WarningAsError", 101_044)
	InvalidArguments            = NewStandardErrorCode(UserError, "InvalidArguments", 101_045)
	ParserError                 = NewStandardErrorCode(UserError, "ParserError", 101_046)
	TypeIncompatible            = NewStandardErrorCode(UserError, "TypeIncompatible", 101_047)

	// 102000~102999 for SynapseDB Internal Error
	GenericInternalError            = NewStandardErrorCode(InternalError, "GenericInternalError", 102_000)
	TooManyRequestsFailed           = NewStandardErrorCode(InternalError, "TooManyRequestsFailed", 102_001)
	PageTooLarge                    = NewStandardErrorCode(InternalError, "PageTooLarge", 102_002)
	PageTransportError              = NewStandardErrorCode(InternalError, "PageTransportError", 102_003)
	PageTransportTimeout            = NewStandardErrorCode(InternalError, "PageTransportTimeout", 102_004)
	NoNodesAvailable                = NewStandardErrorCode(InternalError, "NoNodesAvailable", 102_005)
	RemoteTaskError                 = NewStandardErrorCode(InternalError, "RemoteTaskError", 102_006)
	CompilerError                   = NewStandardErrorCode(InternalError, "CompilerError", 102_007)
	RemoteTaskMismatch              = NewStandardErrorCode(InternalError, "RemoteTaskMismatch", 102_008)
	ServerShuttingDown              = NewStandardErrorCode(InternalError, "ServerShuttingDown", 102_009)
	FunctionImplementationMissing   = NewStandardErrorCode(InternalError, "FunctionImplementationMissing", 102_010)
	RemoteBufferCloseFailed         = NewStandardErrorCode(InternalError, "RemoteBufferCloseFailed", 102_011)
	ServerStartingUp                = NewStandardErrorCode(InternalError, "ServerStartingUp", 102_012)
	FunctionImplementationError     = NewStandardErrorCode(InternalError, "FunctionImplementationError", 102_013)
	InvalidProcedureDefinition      = NewStandardErrorCode(InternalError, "InvalidProcedureDefinition", 102_014)
	ProcedureCallFailed             = NewStandardErrorCode(InternalError, "ProcedureCallFailed", 102_015)
	AmbiguousFunctionImplementation = NewStandardErrorCode(InternalError, "AmbiguousFunctionImplementation", 102_016)
	AbandonedTask                   = NewStandardErrorCode(InternalError, "AbandonedTask", 102_017)
	CorruptSerializedIdentity       = NewStandardErrorCode(InternalError, "CorruptSerializedIdentity", 102_018)
	CorruptPage                     = NewStandardErrorCode(InternalError, "CorruptPage", 102_019)
	OptimizerTimeout                = NewStandardErrorCode(InternalError, "OptimizerTimeout", 102_020)
	OutOfSpillSpace                 = NewStandardErrorCode(InternalError, "OutOfSpillSpace", 102_021)
	RemoteHostGone                  = NewStandardErrorCode(InternalError, "RemoteHostGone", 102_022)
	ConfigurationInvalid            = NewStandardErrorCode(InternalError, "ConfigurationInvalid", 102_023)
	ConfigurationUnavailable        = NewStandardErrorCode(InternalError, "ConfigurationUnavailable", 102_024)
	InvalidResourceGroup            = NewStandardErrorCode(InternalError, "InvalidResourceGroup", 102_025)
	GenericRecoveryError            = NewStandardErrorCode(InternalError, "GenericRecoveryError", 102_026)
	TooManyTaskFailed               = NewStandardErrorCode(InternalError, "TooManyTaskFailed", 102_027)
	IndexLoaderTimeout              = NewStandardErrorCode(InternalError, "IndexLoaderTimeout", 102_028)
	ExceededTaskUpdateSizeLimit     = NewStandardErrorCode(InternalError, "ExceededTaskUpdateSizeLimit", 102_029)
	NodeSelectionNotSupported       = NewStandardErrorCode(InternalError, "NodeSelectionNotSupported", 102_030)
	SpoolingStorageError            = NewStandardErrorCode(InternalError, "SpoolingStorageError", 102_031)
	SerializedPageCheckSumError     = NewStandardErrorCode(InternalError, "SerializedPageCheckSumError", 102_032)
	RetryQueryNotFound              = NewStandardErrorCode(InternalError, "RetryQueryNotFound", 102_033)
	DistributedTracingError         = NewStandardErrorCode(InternalError, "DistributedTracingError", 102_034)
	GenericSpillFailure             = NewStandardErrorCode(InternalError, "GenericSpillFailure", 102_035)
	InvalidPlanError                = NewStandardErrorCode(InternalError, "InvalidPlanError", 102_036)
	DiagnosisError                  = NewStandardErrorCode(UserError, "DiagnosisError", 102_037)

	// 103000~103999 for Resource Insufficient Error
	GenericInsufficientResources          = NewStandardErrorCode(InsufficientResource, "GenericInsufficientResources", 103_000)
	ExceededGlobalMemoryLimit             = NewStandardErrorCode(InsufficientResource, "ExceededGlobalMemoryLimit", 103_000)
	QueryQueueFull                        = NewStandardErrorCode(InsufficientResource, "QueryQueueFull", 103_001)
	ExceededTimeLimit                     = NewStandardErrorCode(InsufficientResource, "ExceededTimeLimit", 103_002)
	ClusterOutOfMemory                    = NewStandardErrorCode(InsufficientResource, "ClusterOutOfMemory", 103_003)
	ExceededCpuLimit                      = NewStandardErrorCode(InsufficientResource, "ExceededCpuLimit", 103_004)
	ExceededSpillLimit                    = NewStandardErrorCode(InsufficientResource, "ExceededSpillLimit", 103_005)
	ExceedLocalMemoryLimit                = NewStandardErrorCode(InsufficientResource, "ExceedLocalMemoryLimit", 103_006)
	AdministrativelyPreempted             = NewStandardErrorCode(InsufficientResource, "AdministrativelyPreempted", 103_007)
	ExceededScanRawBytesReadLimit         = NewStandardErrorCode(InsufficientResource, "ExceededScanRawBytesReadLimit", 103_008)
	ExceededOutputSizeLimit               = NewStandardErrorCode(InsufficientResource, "ExceededOutputSizeLimit", 103_009)
	ExceededRevocableMemoryLimit          = NewStandardErrorCode(InsufficientResource, "ExceededRevocableMemoryLimit", 103_010)
	ExceededLocalBroadcastJoinMemoryLimit = NewStandardErrorCode(InsufficientResource, "ExceededLocalBroadcastJoinMemoryLimit", 103_011)

	// 200000~200999 external mysql error, TODO to define more if necessary
	GenericMysqlError = NewStandardErrorCode(ExternalError, "GenericMysqlError", 200_000)

	// 201000~201999 external arango error, TODO to define more if necessary
	GenericArangoError = NewStandardErrorCode(ExternalError, "GenericArangoError", 201_000)

	// 202000~202999 external redis error , TODO to define more if necessary
	GenericRedisError = NewStandardErrorCode(ExternalError, "GenericRedisError", 202_000)

	// 203000~203999 external Ipfs error, TODO to define more if necessary
	GenericIpfsError = NewStandardErrorCode(ExternalError, "GenericIpfsError", 203_000)

	// 203000~203999 external Ipds error, TODO to define more if necessary
	GenericIpdsError = NewStandardErrorCode(ExternalError, "GenericIpdsError", 204_000)
)
